### PR TITLE
Change min delta

### PR DESCRIPTION
**Pull request by jiangweiyao**
Changed min-delta default to 1 to accommodate shorter index reads. Also updated and fixed small errors in README.

### CODE REVIEW

**Review by nh13 — CHANGES_REQUESTED** [review]
I think changing this value by default is a footgun, and may lead to false assignment of reads to samples, especially with similar barcodes. 

I would recommend either the value is overridden by the end user, as they know the length of barcodes ahead of time.

Alternatively, we change these values to “None” (not specified) and they are fixed based on sample barcode length (e.g. delay is 1 for 10bp barcodes or fewer, 2 for higher etc. I am making these up). 

Can you provide some reasoning why we want to change the default, which will certainly affect folks without shorter indexes?

**Comment by nh13** [comment]
@jiangweiyao if they're not using the tool directly, then I would make the change the software/UI that calls this tool.  If there a user of the tool directly, but not a Bioinformatician (that's questionable given their using this tool directly), then perhaps we can have very big warning instead of changing the default?

**Comment by jiangweiyao** [comment]
How hard would be it to set min-delta and mismatched allowed on a per index read bases? For example, the default is 1 mismatched allowed and 1 min-delta for each index read. So 1/1 for single index and 2/2 for dual index? This would be similar to bcl2fastq as well.

**Comment by nh13** [comment]
There was a conscious choice from the start _not to_ treat each index read separately when matching, but instead apply max-mismatches and min-delta across the concatenated barcode.  Consider the two scenarios: (1) you have one mismatch in both index reads, (2) you have two mismatches in one index read and zero mismatches in the other.  If max-mismatches was 1, then the first scenario you'd carry forward the read while in the second scenario you would not.  Why should they be treated differently, other than "that's how bcl2fastq" does it?

As for how hard it is it to implement, it's unclear as [currently the barcode is concatenated early on](https://github.com/Singular-Genomics/singular-demux/blob/207b0c25962c75f0972123011cd4da094ba8a29f/src/lib/sample_metadata.rs#L53C12-L53C12) for speed.  We'd have to think about how to either (a) do not concatenate sample barcodes across reads (index or R1/R2) and perform independent matching, or (b) post-filter the matches somehow (if that even works).
It probably would take a few hours to figure out what's possible and what would be performant.

Why not just have the instrument software determine the correct values for max-mismatches and min-delta and feed them in to the tool?  No modifications needed here, and a nice separation of concerns?

What's the reason for matching each index read independently?  Does one index read have substantially worse quality than the other?

**Pull request closed without merging**
